// Represents a row in the public.food_items table.
// This is the food database that users pick from when logging a meal.
// All 44 seeded items (Chicken Breast, Rice, Banana, etc.) are public foods with
// is_public = true and created_by_user_id = NULL.
//
// The nutritional values are all per 100g, so the app can scale them to the actual
// portion size the user enters (e.g. 150g of chicken = 150/100 * 165 = 247.5 calories).
// NOTE: calorie calculation is not yet implemented in the app — currently only grams are shown.

using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace SmartMeal.core.Models
{
    [Table("food_items")]
    public class FoodItem : BaseModel
    {
        // Auto-generated by the database. Used as the foreign key in meal_logs.food_id.
        [PrimaryKey("food_id")]
        public long FoodId { get; set; }

        // The human-readable name shown in the food dropdown on AddMealView.
        [Column("name")]
        public string Name { get; set; } = string.Empty;

        // Links this food to a category (e.g. 1 = Protein, 2 = Carbs).
        // Nullable: USDA-sourced foods inserted by users don't have a matching local category,
        // so we store null for them. The category name is not displayed anywhere in the UI yet.
        [Column("food_category_id")]
        public short? FoodCategoryId { get; set; }

        // All nutrition values are per 100g of this food.
        // To get the actual value for a serving: (grams / 100) * value_per_100g.
        [Column("calories_per_100g")]
        public decimal CaloriesPer100g { get; set; }

        [Column("protein_per_100g")]
        public decimal ProteinPer100g { get; set; }

        [Column("carbs_per_100g")]
        public decimal CarbsPer100g { get; set; }

        [Column("fats_per_100g")]
        public decimal FatsPer100g { get; set; }

        // Only public, active foods are shown in the dropdown (FoodService filters by both).
        // is_public = true means anyone can see this item (seeded foods are all public).
        // is_active = false is how a food is "soft deleted" without removing the row.
        [Column("is_public")]
        public bool IsPublic { get; set; }

        [Column("is_active")]
        public bool IsActive { get; set; }

        // Set when a user adds a food from the USDA search; null for seeded public foods.
        // DB constraint: public foods must have this NULL; private foods must have it set.
        [Column("created_by_user_id")]
        public string? CreatedByUserId { get; set; }

        [Column("created_at")]
        public DateTime CreatedAt { get; set; }
    }
}
