// Represents a row in the public.goals table.
// Each user has at most ONE goal row — the database enforces this with a UNIQUE constraint
// on user_id. When a user sets a new goal, we UPDATE the existing row rather than inserting
// a new one (see GoalService.UpsertGoalAsync for how this works).
//
// The table supports richer goals (target weight, protein, carbs, fat targets) but the
// current UI only collects and displays calorie_goal. The other columns exist and are
// ready to use — they just need a UI form to go with them.

using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace SmartMeal.core.Models
{
    [Table("goals")]
    public class Goal : BaseModel
    {
        // Auto-generated by the database. Not used directly by the app
        // (we look up goals by user_id, not by goal_id).
        [PrimaryKey("goal_id")]
        public long GoalId { get; set; }

        // The user this goal belongs to. One-to-one with users.id.
        // If the user account is deleted, this goal row is also deleted (ON DELETE CASCADE).
        [Column("user_id")]
        public string UserId { get; set; } = string.Empty;

        // How much the user wants to weigh. Not collected by the UI yet.
        [Column("target_weight_kg")]
        public decimal? TargetWeightKg { get; set; }

        // The daily calorie target. This is the only field the SetGoalView currently sets.
        // Stored as decimal? (nullable) because a brand-new row might not have this set.
        [Column("calorie_goal")]
        public decimal? CalorieGoal { get; set; }

        // Macro targets — all nullable, all currently unset by the UI.
        // These columns are ready in the database whenever the UI is built out.
        [Column("protein_goal")]
        public decimal? ProteinGoal { get; set; }

        [Column("carbs_goal")]
        public decimal? CarbsGoal { get; set; }

        [Column("fat_goal")]
        public decimal? FatGoal { get; set; }

        // When this goal was first created. Set in C# on insert.
        [Column("created_at")]
        public DateTime CreatedAt { get; set; }
    }
}
