// Represents a row in the public.meal_logs table.
// Every time a user logs "I ate 150g of chicken breast at breakfast", one MealLog row is created.
// It stores the who (user_id), the what (food_id), the how much (grams),
// the when (log_date), and the which meal (meal_type_id).
//
// To display meaningful information from this model (e.g. the food name or meal type name),
// you need to cross-reference with the food_items and meal_types tables.
// Currently the app just shows the raw IDs — joining for display is a planned improvement.

using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace SmartMeal.core.Models
{
    [Table("meal_logs")]
    public class MealLog : BaseModel
    {
        // Auto-generated by the database. Used as the Tag on delete buttons in MealsView
        // so we know exactly which row to delete when the user clicks Delete.
        [PrimaryKey("meal_log_id")]
        public long MealLogId { get; set; }

        // The UUID of the user who logged this meal. Comes from AuthService.CurrentUser.Id.
        // Foreign key to users.id — if the user account is deleted, all their meal logs
        // are automatically deleted too (ON DELETE CASCADE).
        [Column("user_id")]
        public string UserId { get; set; } = string.Empty;

        // Which food was eaten. Foreign key to food_items.food_id.
        // ON DELETE RESTRICT means you cannot delete a food item if any meal logs reference it.
        [Column("food_id")]
        public long FoodId { get; set; }

        // How many grams of the food were eaten. Must be greater than 0 (DB constraint).
        [Column("grams")]
        public decimal Grams { get; set; }

        // Which meal period this belongs to (1=Breakfast, 2=Lunch, 3=Dinner, 4=Snack).
        // Foreign key to meal_types.meal_type_id.
        [Column("meal_type_id")]
        public short MealTypeId { get; set; }

        // The date the meal was eaten, stored as a string in "yyyy-MM-dd" format.
        // We use string instead of DateOnly because the Supabase C# ORM serialises
        // dates as strings over the REST API. The default initialises to today's date
        // so a new MealLog object is always pre-filled with the correct date.
        // The DB column type is DATE, which PostgreSQL accepts in this format.
        [Column("log_date")]
        public string LogDate { get; set; } = DateOnly.FromDateTime(DateTime.Now).ToString("yyyy-MM-dd");

        // Timestamp of when this record was created. The database sets this automatically
        // via DEFAULT now(), but we also set it in C# so the local object is accurate
        // immediately after creation (before the DB response comes back).
        [Column("created_at")]
        public DateTime CreatedAt { get; set; }
    }
}
