// Represents a row in the public.weight_logs table.
// This table is designed to track a user's weight over time — each entry is a
// timestamped weigh-in with an optional note (e.g. "After morning workout").
//
// The model is fully mapped and WeightLogService now handles persistence/query logic,
// but there is currently no UI screen to log or view weight history.

using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace SmartMeal.core.Models
{
    [Table("weight_logs")]
    public class WeightLog : BaseModel
    {
        // Auto-generated by the database.
        [PrimaryKey("weight_log_id")]
        public long WeightLogId { get; set; }

        // The user this weigh-in belongs to. Deleting a user also deletes all their weight logs.
        [Column("user_id")]
        public string UserId { get; set; } = string.Empty;

        // The recorded weight in kilograms. Must be greater than 0 (DB constraint).
        [Column("weight_kg")]
        public decimal WeightKg { get; set; }

        // When the weight was recorded. Unlike meal logs (which use a DATE), this stores
        // a full timestamp so multiple weigh-ins on the same day can be distinguished.
        [Column("logged_at")]
        public DateTime LoggedAt { get; set; }

        // An optional free-text note the user can attach to a weigh-in.
        // Nullable — not required.
        [Column("notes")]
        public string? Notes { get; set; }
    }
}
